# DataSource Config
spring:
  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
#    url: jdbc:mysql://192.168.0.110:3306/hcwblog?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=UTC
    url: jdbc:p6spy:mysql://192.168.0.110:3306/hcwblog?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=UTC
    username: hcwblog
    password: DuNiTGxr.2Qp5WcV
mybatis-plus:
  mapper-locations: classpath*:/mapper/**Mapper.xml





