# DataSource Config
spring:
  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
#    url: jdbc:mysql://192.168.0.110:3306/hcwblog?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    url: jdbc:p6spy:mysql://192.168.0.110:3306/hcwblog?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: hcwblog
    password: DuNiTGxr.2Qp5WcV
  session:
      store-type: redis
      timeout: 3600s
      redis:
        flush-mode: on_save
        namespace: spring:session
# redis配置
  redis:
    host: 192.168.0.110
    port: 6379
    password: Zhang123.
#mybatis配置
mybatis-plus:
  mapper-locations: classpath*:/mapper/**Mapper.xml

# 七牛云存储
oss:
  qiniu:
    domain: https://img.hcworld.xyz # 访问域名(默认使用七牛云测试域名)
    accessKey: XXXXX # 公钥
    secretKey: XXXXX # 私钥
    bucketName: wxworld  #存储空间名称



